### PR TITLE
admin/message-log: reflect sent time in sort order

### LINKED ISSUE #2650: admin: message log does not reflect sent time
**Describe the Bug:**
Currently, the message logs admin tool displays and sorts based on `created_at` time only, ignoring `sent_at`.

This is important in cases where messages are being throttled or retried since throttling is based on `sent_at`.

**Expected Behavior:**
Sort by `created_at` IF `sent_at` is null; otherwise, sort by `sent_at`, keeping unsent messages at the top.

**Observed Behavior:**
Sort is purely based on `created_at` time, sent time, and retries, all are not available.

### PR DESCRIPTION
**Pull request by cmarquis**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
The admin message log will now display messages that have not yet been sent at the top of the list and then sort by the created time thereafter. 

**Which issue(s) this PR fixes:**
Fixes #2650 

**Describe any introduced user-facing changes:**
- The sorting of the admin message logs was affected as described in the description above.
- Added the sent at time to the message details
- Added the retry count to the message details, if greater than 0

**Describe any introduced API changes:**
Added `sentAt` and `retryCount` to the `DebugMessage` type.

**Additional Info:**
- Updated the sql query and model to retrieve the `sent_at` and `retry_count` values from the database
- Updated the sql query to sort messages first by any messages where `sent_at` is null and then `created_at`
- Added a new smoke test to validate the sorting is being applied properly

### CODE REVIEW

File: graphql2/graphqlapp/messagelog.go [hunk 1]
```diff
@@ -211,6 +212,9 @@ func (q *Query) MessageLogs(ctx context.Context, opts *graphql2.MessageLogSearch
 		if log.ProviderMsgID != nil {
 			dm.ProviderID = &log.ProviderMsgID.ExternalID
 		}
+		if log.SentAt != nil {
+			dm.SentAt = log.SentAt
+		}
```
Comment (mastercactapus) [inline graphql2/graphqlapp/messagelog.go:217]: These can both be nil, so the `if` check isn't necessary.
```suggestion
		dm.SentAt = log.SentAt
```

File: notification/search.go [hunk 2]
```diff
@@ -98,7 +102,7 @@ var searchTemplate = template.Must(template.New("search").Funcs(search.Helpers()
 		OR (om.created_at = :cursorCreatedAt AND om.id > :afterID)
 	{{end}}
 		AND om.last_status != 'bundled'
-	ORDER BY om.created_at desc, om.id asc
+	ORDER BY (CASE WHEN om.sent_at IS NULL THEN 1 ELSE 0 END) desc, om.created_at desc, om.id asc
```
Comment (mastercactapus) [inline notification/search.go:105]: Hmm, this won't entirely give us what we want -- there are failure scenarios where `sent_at` will always be NULL; we also want to sort by the value of `sent_at` and not _only_ if it's null or not.

What about doing `sent_at` but falling back to `last_status_at`? That way, as messages are retried/updated, they will bounce to the top but, once sent, will keep their place.

Also, any messages with the `PENDING` state should probably stay at the top, since those can be important to consider.


```suggestion
	ORDER BY om.last_status = 'pending' desc, coalesce(om.sent_at, om.last_status_at) desc, om.created_at desc, om.id asc
```

**Review by mastercactapus — CHANGES_REQUESTED** [review]

File: graphql2/graphqlapp/messagelog.go (hunk 1 above)
Comment (cmarquis) [reply graphql2/graphqlapp/messagelog.go]: Moved the setting of dm.SentAt into the struct instantiation.

File: notification/search.go (hunk 2 above)
Comment (cmarquis) [reply notification/search.go]: That makes sense. Change made and test updated as well.

**Review by Forfold — APPROVED** [review]

**Review by mastercactapus — APPROVED** [review]
