### PR TITLE
fix items being filtered from options list

### LINKED ISSUE #2701: ui: userselect search display on no results
when there are no results when typing in a UserSelect formfield, the placeholder text *_sometimes_* displays "Start typing..." instead of "No options"

screenshots:

empty state

Screen Shot 2022-11-28 at 10 46 21 AM

with results state

Screen Shot 2022-11-28 at 10 46 31 AM

no results state

Screen Shot 2022-11-28 at 10 46 54 AM

expected behavior:
display "No options" after searching and array is still empty

### PR DESCRIPTION
**Pull request by Forfold**
Closes #2701

`AutoComplete` filters out options that don't match the value, so adding an override that passes all options through the menu resolves this:

before:

Screen Shot 2022-11-28 at 10 46 54 AM

after:

Screen Shot 2022-11-28 at 12 05 18 PM

### CODE REVIEW

**Review by mastercactapus — DISMISSED** [review]

**Review by tony-tvu — DISMISSED** [review]

File: web/src/app/selection/MaterialSelect.tsx [hunk 1]
```diff
@@ -164,11 +164,12 @@ export default function MaterialSelect(
       data-cy-ready={!isLoading}
       classes={customCSS}
       multiple={multiple}
-      filterSelectedOptions={multiple}
+      filterSelectedOptions
```
Comment (mastercactapus) [inline web/src/app/selection/MaterialSelect.tsx:167]: This was necessary so that searching for a value in single-select mode won't omit the current one -- since there is no indicator that it's currently selected otherwise (in multiple, the chip is displayed).

**Review by mastercactapus — CHANGES_REQUESTED** [review]

File: web/src/app/selection/MaterialSelect.tsx (hunk 1 above)
Comment (Forfold) [reply web/src/app/selection/MaterialSelect.tsx:167]: @mastercactapus I noticed that even though this was on for single items, it wasn't working as intended- the selected item would show with the default load, but if I typed in a search term, my selected item wouldn't be visible anymore. I made this change after I noticed my Cypress tests fail- so hopefully with this change it resolves that:

default when clicking on select (with GoAlert selected)

Screen Shot 2022-12-05 at 9 19 20 AM


items after searching (with  GoAlert still selected)

Screen Shot 2022-12-05 at 9 19 35 AM

**Review by mastercactapus — DISMISSED** [review]

File: web/src/app/selection/MaterialSelect.tsx (hunk 1 above)
Comment (Forfold) [reply web/src/app/selection/MaterialSelect.tsx]: Talked offline- going to keep the filter as it was before and update the other tests that failed to reflect the new functionality.

**Review by mastercactapus — APPROVED** [review]

**Review by KatieMSB — APPROVED** [review]
