### PR TITLE
ui/lists: fix FAB margins

### LINKED ISSUE #1550: ui: FAB margins are inconsistent
**Describe the Bug:**
There is a regression with the bottom corner FABs having different margins on different pages

**Steps to Reproduce:**
1. Go to /alerts
2. Go to /rotations
3. Observe different margins

**Expected Behavior:**
FABs use a consistent margin, ideally specified by [material design](https://material.io/components/buttons-floating-action-button)

**Observed Behavior:**
See below

**Screenshots/Stack Traces:**
Screen Shot 2021-05-18 at 7 35 43 AM
Screen Shot 2021-05-18 at 7 38 09 AM

**Application Version:**
`731a07bd869ea4bbb0c8bf6ad6ff7edf169ec0cb`

### PR DESCRIPTION
**Pull request by dctalbot**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR make all create FABs use the same margin as defined by material design (16dp). 

- Removes `CreateAlertFab` in favor of `CreateFAB`
- Adjust margin to 16px
- Adjust Speeddial margin to match

**Which issue(s) this PR fixes:**
Fixes #1550

### CODE REVIEW

File: web/src/app/alerts/AlertsList.js [hunk 1]
```diff
@@ -92,9 +93,10 @@ function getStatusFilter(s) {
 export default function AlertsList(props) {
   const classes = useStyles()
   const width = useWidth()
-  const isMobileScreenSize = isWidthDown('md', width)
+  const isMobileScreenSize = isWidthDown('xs', width)
```
Comment (Forfold) [inline web/src/app/alerts/AlertsList.js:96]: We're using `'sm'` in `App.js` to determine whether we're in a mobile size or not, and `'md'` in most other places. This should probably be `'sm'` to best reflect `App.js`

**Review by Forfold — CHANGES_REQUESTED** [review]

File: web/src/app/alerts/AlertsList.js (hunk 1 above)
Comment (Forfold) [reply web/src/app/alerts/AlertsList.js:96]: Is this a current bug in production?

Comment (Forfold) [reply web/src/app/alerts/AlertsList.js:96]: If this is only being used for the transition on the create fab, I think it'd make more sense to just rename it to something else, since it's only being used when the snackbar has the potential to overlap with its intended placement, rather than if it's mobile or not

Comment (dctalbot) [reply web/src/app/alerts/AlertsList.js:96]: Yeah, we could either extend with of the snack bar on `sm`, or use what I have at the moment

Comment (Forfold) [reply web/src/app/alerts/AlertsList.js:96]: I'm fine with what we have for the moment, the name just threw me off which is why I commented that we use sm/md normally. Probably how the bug got introduced in the first place if I had to guess. Maybe?:
```suggestion
  // used to transition fab above snackbar when snackbar width overlaps fab placement
  const isXS = isWidthDown('xs', width)
```

Comment (dctalbot) [reply web/src/app/alerts/AlertsList.js:96]: Yeah, we can clear up the naming. Might be an opportunity for us to write our own `useViewport`

```js
const {isMobile, isPhablet, isTablet, isDesktop, isWidescreen} = useViewport()
```

Would help keep things consistent

Comment (Forfold) [reply web/src/app/alerts/AlertsList.js]: That would be really convenient. I've been wanting to make an issue around our general layout and making our own, usable breakpoints, but don't have a concrete design yet. Def need to remember this for that!

**Review by Forfold — APPROVED** [review]

**Review by Forfold — APPROVED** [review]

**Review by KatieMSB — APPROVED** [review]
