### PR TITLE
fix for go 1.19

### LINKED ISSUE #2562: Incompatible with Golang 1.19
**Describe the Bug:**
App does not pass checks or compile when using golang 1.19

**Steps to Reproduce:**
```bash
make check
```
Result:
```
devtools/gettool/fetchfile.go:6:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
grafana/grafana.go:7:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
notification/twilio/twiml_test.go:4:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
smoketest/webhook_test.go:6:2: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)
exit status 1
make: *** [check] Error 1
```

**Expected Behavior:**
make check should work without errors

**Observed Behavior:**
make check fails

**Screenshots/Stack Traces:**
If applicable, add screenshots and/or stack traces to help explain your problem.

**Application Version:**
goalert master branch

**Desktop:**
NA

**Smartphone/Tablet:**
NA

**Additional Context:**

### PR DESCRIPTION
**Pull request by AlaricWhitney**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Updated deprecated ioutils to work with go 1.19

**Which issue(s) this PR fixes:**
https://github.com/target/goalert/issues/2562

Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
Fixes #2562 

**Out of Scope:**
NA

**Screenshots:**
NA

**Describe any introduced user-facing changes:**
NA

**Describe any introduced API changes:**
NA

**Additional Info:**
NA

### CODE REVIEW

File: smoketest/webhook_test.go [hunk 1]
```diff
@@ -2,12 +2,13 @@ package smoketest
...
 	"encoding/json"
-	"github.com/stretchr/testify/require"
-	"io/ioutil"
+	"io"
 	"net/http"
 	"net/http/httptest"
 	"testing"
 
+	"github.com/stretchr/testify/require"
+
```
Comment (mastercactapus) [inline smoketest/webhook_test.go:11]: nit: remove extra newline

**Review by mastercactapus — APPROVED** [review]

**Review by KatieMSB — APPROVED** [review]
