### PR TITLE
fix: material select shows selected option in dropdown for single-select

### LINKED ISSUE #958: ui: "No options" is rendered when a single select field is open with a value set
> In single select dropdowns, "No options" is rendered when a value is set.

_Originally posted by @mastercactapus in https://github.com/target/goalert/pull/925#discussion_r501285735_

Additional Cypress tests should also be created. Currently, only clearing the fields for single and multiple selects is covered.

### LINKED ISSUE #994: material select: omits selected option from options dropdown in single-select mode
**Describe the Bug:**
Provide a clear, concise description of the issue and why you consider it to be a bug.

**Steps to Reproduce:**
1. Go to rotations, create, timezone
2. America/Chicago (default for me) does not appear in dropdown list since it's the selected value

**Expected Behavior:**
Selected option should appear in dropdowns

**Observed Behavior:**
Selected option does not appear in dropdowns

### PR DESCRIPTION
**Pull request by dctalbot**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR fixes an issue in the autocomplete select component in which the stateful selected option would not render as an option in the dropdown.

**Which issue(s) this PR fixes:**
Closes #994 and closes #958

**Screenshots:**
Screen Shot 2020-11-05 at 11 53 26 AM

### CODE REVIEW

**Review by KatieMSB — CHANGES_REQUESTED** [review]
Should probably add new Cypress tests as mentioned in #958.

**Review by KatieMSB — DISMISSED** [review]

File: web/src/cypress/integration/materialSelect.ts [hunk 1]
```diff
@@ -96,6 +96,22 @@ function testMaterialSelect(): void {
       })
     })
   })
+
+  describe('render options', () => {
+    it.only('should show selected value as an option in single-select mode', () => {
```
Comment (mastercactapus) [inline web/src/cypress/integration/materialSelect.ts:101]:
```suggestion
    it('should show selected value as an option in single-select mode', () => {
```

File: web/src/app/selection/MaterialSelect.tsx [hunk 2]
```diff
@@ -105,22 +105,26 @@ export default function MaterialSelect(
...
-  if (value) {
-    // merge options with value
-    options = options.concat(Array.isArray(value) ? value : [value])
+  let options = _options
+  if (value && Array.isArray(value)) {
+    options = [...options, ...value]
+  } else if (
+    value &&
+    !Array.isArray(value) &&
+    options.every((opt) => opt.value !== value.value)
```
Comment (mastercactapus) [inline web/src/app/selection/MaterialSelect.tsx:125]: Should we be doing this check for the array form too?

**Review by mastercactapus — CHANGES_REQUESTED** [review]

File: web/src/app/selection/MaterialSelect.tsx (hunk 2 above)
Comment (dctalbot) [reply web/src/app/selection/MaterialSelect.tsx:125]: No, this handles the case for when the input is re-selected. Without this check, you'd end up with this:
Screen Shot 2020-11-06 at 10 09 49 AM
So we do an explicit check to say "only add value to the list of options if it's not already an option".
This isn't an issue in multi-select since there is no concept of "re-selecting" (`filterSelectedOptions` is turned on). Thanks for checking!

File: web/src/cypress/integration/materialSelect.ts (hunk 1 above)
Comment (dctalbot) [reply web/src/cypress/integration/materialSelect.ts]: Thank you :)

File: web/src/app/selection/MaterialSelect.tsx (hunk 2 above)
Comment (mastercactapus) [reply web/src/app/selection/MaterialSelect.tsx:125]: Ty for the clarification!

**Review by mastercactapus — APPROVED** [review]

**Review by KatieMSB — APPROVED** [review]
