### PR TITLE
graphql/playground: fix graphql playground schema

### LINKED ISSUE #1040: graphql: playground schema broken
**Describe the Bug:**
Clicking on "SCHEMA" in the GraphQL playground breaks the page.

**Steps to Reproduce:**
1. Go to '/api/graphql/explore'
2. Click on 'SCHEMA' on the right
4. Page goes blank, error in console

**Expected Behavior:**
Schema should be displayed

**Observed Behavior:**
Page breaks

**Application Version:**
GoAlert v0.26.0 (playground is 1.7.23)

### PR DESCRIPTION
**Pull request by KatieMSB**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Updates graphql playground dependency from `graphql-playground-react` to `@apollographql/graphql-playground-react`.

**Which issue(s) this PR fixes:**
Fixes #1040

### CODE REVIEW

File: graphql2/graphqlapp/app.go [hunk 1]
```diff
@@ -94,8 +94,10 @@ func mustAuth(h http.Handler) http.Handler {
 func (a *App) PlayHandler() http.Handler {
 	var data struct {
 		Version string
+		Url     string
```
Comment (mastercactapus) [inline graphql2/graphqlapp/app.go:97]: maybe name this `PackageName`

**Review by mastercactapus — CHANGES_REQUESTED** [review]

**Review by dctalbot — APPROVED** [review]
LGTM :D

**Review by mastercactapus — CHANGES_REQUESTED** [review]
This doesn't seem to work for me:
image

**Review by mastercactapus — APPROVED** [review]
