### PR TITLE
fix: aligning esc policy notices

### LINKED ISSUE #3197: ui: notice padding/margin off with rest of page
**Describe the Bug:**
Screenshot 2023-07-25 at 9 28 42 AM

**Steps to Reproduce:**
1. Go to an escalation policy with an active notice

**Expected Behavior:**
- Spacing is in line with cards on all sides

### PR DESCRIPTION
**Pull request by andrewbenington**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
Escalation policy notices now align with the main grid of the details page.

**Which issue(s) this PR fixes:**
Fixes #3197

**Screenshots:**
Before:
Screenshot 2023-07-25 at 11 55 57 AM
After:
Screenshot 2023-07-25 at 11 59 12 AM

### CODE REVIEW

File: web/src/app/details/DetailsPage.tsx [hunk 1]
```diff
@@ -96,7 +96,9 @@ export default function DetailsPage(p: DetailsPageProps): JSX.Element {
   return (
     <Grid container spacing={2}>
       {/* Notices */}
+      <Grid item xs={12}>
       {Array.isArray(p.notices) ? <Notices notices={p.notices} /> : p.notices}
```
Comment (Forfold) [inline web/src/app/details/DetailsPage.tsx:100]:
```suggestion
        {Array.isArray(p.notices) ? <Notices notices={p.notices} /> : p.notices}
```

**Review by Forfold — APPROVED** [review]

**Review by mastercactapus — APPROVED** [review]
