### PR TITLE
ui/escalation-policies: sort services by name

### LINKED ISSUE #1460: ui/escalation policies: services list order is unstable
**Steps to Reproduce:**
1. Go to /escalation-policies/:id/services
2. Observe flickering of list item order (sometimes)

**Expected Behavior:**
List order is sorted reliably

**Observed Behavior:**
List flickers as items are shuffled

**Application Version:**
`a5325e223fe6cb639b8144e05a31ae71443a23e4`

### PR DESCRIPTION
**Pull request by dctalbot**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This sorts the policy services by name to prevent shuffling by apollo polling

**Which issue(s) this PR fixes:**
fixes #1460 

**Describe any introduced user-facing changes:**
Users will not see the listed items spontaneously change order

### CODE REVIEW

File: web/src/app/escalation-policies/PolicyServicesCard.tsx [hunk 1]
```diff
@@ -1,24 +1,31 @@
...
 
-  function getServicesItems() {
-    return props.services.map((service) => ({
+  function getServicesItems(): FlatListListItem[] {
+    const items = props.services.map((service) => ({
       title: service.name,
       url: `/services/${service.id}`,
     }))
+
+    return _.sortBy(items, 'title')
```
Comment (Forfold) [inline web/src/app/escalation-policies/PolicyServicesCard.tsx:26]: I'm noticing titles starting with 'a' are prioritized after all uppercase items, rather than as `AaBbCc`. I don't see this as a major issue really but we _do_ sort our paginated lists as `AaBbCc`. Does lodash accept any sort options?

Comment (Forfold) [reply web/src/app/escalation-policies/PolicyServicesCard.tsx:26]: e.g.

Screen Shot 2021-04-27 at 2 08 27 PM

Comment (mastercactapus) [reply web/src/app/escalation-policies/PolicyServicesCard.tsx]: Something like this might work:
```
_.sortBy(items, [i=>i.title.toLowerCase(), i=>i.title])
```

Comment (mastercactapus) [reply web/src/app/escalation-policies/PolicyServicesCard.tsx]: Though our unique constrains are all case-insensitive so `_.sortBy(items, i=>i.title.toLowerCase())` would also be sufficient

**Review by mastercactapus — APPROVED** [review]

**Review by Forfold — APPROVED** [review]
