### PR TITLE
fix: memoize calendar event handlers to prevent tooltip flicker

### LINKED ISSUE #959: temporary schedules: calendar tooltip flickers
**Describe the Bug:**
On the `feature/temp-schedules` branch:
When hovering over a shift, temporary or not, the tooltip, and associated controls, flicker on data update making it difficult to read and use the controls, like edit/delete.

**Steps to Reproduce:**
1. Go to a schedule details page
2. Hover over a shift, you should see a tooltip
3. Wait a few seconds for the data refresh
4. Observe the tooltip flickering in and out of existence

**Expected Behavior:**
The tooltip should remain visible as the data refreshes in the background.

**Observed Behavior:**
The tooltip flickers multiple times when the data refreshes.

**Screenshots/Stack Traces:**
image

**Application Version:**
`feature/temp-schedules` branch

### PR DESCRIPTION
**Pull request by dctalbot**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
To prevent unnecessary remounting of calendar event wrappers, we can memoize the event handlers here

Fixes #959

### CODE REVIEW

File: web/src/app/schedules/ScheduleDetails.js [hunk 1]
```diff
@@ -46,6 +46,16 @@ export default function ScheduleDetails({ scheduleID }) {
   const [configTempSchedule, setConfigTempSchedule] = useState(null)
   const [deleteTempSchedule, setDeleteTempSchedule] = useState(null)
 
+  const onNewTempSched = useMemo(() => () => setConfigTempSchedule(true), [])
```
Comment (mastercactapus) [inline web/src/app/schedules/ScheduleDetails.js:49]: Use `useCallback` for these
```suggestion
  const onNewTempSched = useMemo(() => setConfigTempSchedule(true), [])
```

File: web/src/app/schedules/ScheduleDetails.js [hunk 2]
```diff
@@ -46,6 +46,16 @@ export default function ScheduleDetails({ scheduleID }) {
...
+  const onEditTempSched = useMemo(
+    () => (sched) => setConfigTempSchedule(sched),
+    [],
+  )
+  const onDeleteTempSched = useMemo(
+    () => (sched) => setDeleteTempSchedule(sched),
+    [],
+  )
```
Comment (mastercactapus) [inline web/src/app/schedules/ScheduleDetails.js:57]: simplify, also may need to be `handleOnDeleteTempSched` IIRC (linter will say)
```suggestion
  const onDeleteTempSched = useCallback(setDeleteTempSchedule, [])
```

**Review by mastercactapus — CHANGES_REQUESTED** [review]

**Review by Forfold — APPROVED** [review]
lgtm

**Review by pnengchu — APPROVED** [review]
lgtm ⭐

**Review by mastercactapus — APPROVED** [review]
