### PR TITLE
ui/escalation-policies: use NumberField for delay minutes

### LINKED ISSUE #1055: ui: escalation policy step edit dialog has invalid input field hint text
**Describe the Bug:**
When clearing the Delay field on the policy step edit dialog, a user sees "This will cause the step to escalate after NaNm"

**Steps to Reproduce:**
1. Go to an escalation policy
2. Click on edit
3. Clear delay field

**Expected Behavior:**
Hint is either valid or hidden

**Observed Behavior:**
An invalid hint is rendered

**Screenshots/Stack Traces:**
Screen Shot 2020-11-20 at 12 17 23 PM

**Application Version:**
Output of `goalert version` and/or version information from view-source on the UI.

```
Version:   v0.26.0-170-g6c47d5f3
GitCommit: 6c47d5f38aff8f73d7904563f6c8b8c66f95f0d9 (clean)
BuildDate: 2020-11-20T12:15:26-06:00
GoVersion: go1.15.3 (gc)
Platform:  darwin/amd64
Migration: session-last-access-time (#200)
```

### PR DESCRIPTION
**Pull request by dctalbot**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR has the delay minutes form field use the `NumberField` component making it unclearable, preventing invalid hint text.

**Which issue(s) this PR fixes:**
Fixes #1055

**Describe any introduced user-facing changes:**
Users can't clear the field since it is required.

### CODE REVIEW

**Review by mastercactapus — DISMISSED** [review]

File: web/src/app/escalation-policies/PolicyStepForm.js [hunk 1]
```diff
@@ -232,7 +232,7 @@ function PolicyStepForm(props) {
         </Grid>
         <Grid item xs={12}>
           <FormField
-            component={TextField}
+            component={NumberField}
             disabled={disabled}
             fullWidth
             label='Delay (minutes)'
```
Comment (Forfold) [inline web/src/app/escalation-policies/PolicyStepForm.js:238]: We should be able to remove `type` and `mapOnChangeValue` now, as they are handled within `NumberField`

**Review by Forfold — CHANGES_REQUESTED** [review]

**Review by Forfold — APPROVED** [review]

**Review by Forfold — APPROVED** [review]

**Review by arurao — APPROVED** [review]
