### PR TITLE
ui: fix markdown url rendering

### LINKED ISSUE #1268: ui/users: regression in rendering user emails
**Steps to Reproduce:**
1. Go to a user profile
2. See below

**Expected Behavior:**
Render the email address as either plain text or as a "mailto" link

**Observed Behavior:**
See blow

**Screenshots/Stack Traces:**
Screen Shot 2021-02-17 at 1 53 58 PM

**Application Version:**
`761a0b7b878a7a2d269b78016096b7c44266af6c`

### PR DESCRIPTION
**Pull request by dctalbot**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [x] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This PR fixes a regression in displaying markdown links likely introduced by `remark-gfm`

Previously, emails were rejected by `safeURL` and rendered as full plain text (see below image). Tel numbers behaved similarly.

Emails are now rendered as `mailto` links if the email address matches the label, else full plain text. Tel numbers behave similarly but use `tel`. User details are not rendered in markdown.
**Issue this fixes:**
fixes #1268 

Before:
Screen Shot 2021-02-17 at 1 53 58 PM

After:
Screen Shot 2021-02-17 at 1 58 40 PM

Screen Shot 2021-02-23 at 11 42 50 AM
Screen Shot 2021-02-23 at 11 42 56 AM

Screen Shot 2021-02-23 at 1 33 02 PM
Screen Shot 2021-02-23 at 1 32 46 PM

### CODE REVIEW

File: web/src/app/util/Markdown.js [hunk 1]
```diff
@@ -16,6 +16,12 @@ export default function Markdown(props) {
         if (node.type !== 'link') return true
         if (node.children[0].type !== 'text') return true // only validate text labels
         if (safeURL(node.url, node.children[0].value)) return true
+        if (node.url.startsWith('mailto:')) {
+          // do not yield native mailto link, use plain text instead
+          node.type = 'text'
+          delete node.url
+          return true
+        }
```
Comment (mastercactapus) [inline web/src/app/util/Markdown.js:24]: Not sure it's necessary to bar the links everywhere in-app -- this will also prevent `mailto` links from working in descriptions and alert details when added intentionally by users of the application.

I think the goal was only to fix it on the user details page by making it render as text.

**Review by mastercactapus — CHANGES_REQUESTED** [review]

File: web/src/app/util/Markdown.js (hunk 1 above)
Comment (dctalbot) [reply web/src/app/util/Markdown.js:24]: This is an app-wide bug. In the current state, users are already prevented from intentionally adding `mailto` links anywhere in the app since they are rejected by `safeURL`. I think the `remark-gfm` plugin now gives us the capability to use `mailto`, but I didn't think we were turning it on. 

I couldn't think of a compelling scenario wherein allowing `mailto:` links would enhance UX. The `safeURL` logic is also app-wide, so we are already limiting users' abilities to a degree. Happy to entertain other opinions on this :)

Comment (dctalbot) [reply web/src/app/util/Markdown.js:24]: If we _do_ allow custom schemas, we should consider `tel:`, `slack:`, other protocol handlers. And then we need to decide which parts of the app are worthy of these features, and which are not. If User Details is the only concern for now, maybe it shouldn't be in markdown to begin with.

Comment (mastercactapus) [reply web/src/app/util/Markdown.js:24]: For profile maybe something like `noMarkdown` as a flag for `DetailsPage`

As for the others, I wasn't aware that other protocols were broken, that seems like a bug. As far as URLs that are not allowed, it was intentional to render them as raw markdown rather than hide any information.

The primary concern was labels that don't match the URL. In that case a fix could be to allow the label to omit the protocol in the URL so that things like both `[http://example.com](http://example.com)` and `[example.com](http://example.com)` work

File: web/src/app/util/safeURL.ts [hunk 2]
```diff
@@ -2,6 +2,12 @@
 //
 // It tries to determine if the label is misleading.
 export function safeURL(url: string, label: string): boolean {
+  if (url.startsWith('mailto:')) {
+    const email = url.split(':')[1]
```
Comment (mastercactapus) [inline web/src/app/util/safeURL.ts:6]: `:` is allowed in the local part of an address if it's in a quoted string, which could break this
```suggestion
    const email = url.substr(7)
```

**Review by mastercactapus — CHANGES_REQUESTED** [review]
There's no special support required, they just render as anchor tags. We should support `tel` being an on-call app, though that's probably as far as we need to go. Slack supports linking most things through normal http/https links.

A simple check that the number matches should be good enough for `tel`, and should allow decent integration when on a mobile device.
```go
  if (url.startsWith('tel:')) {
    const phone = url.substr(4)
    return phone === label && /^\+?[\d\- ]+$/.test(phone)
  }
```

File: web/src/app/util/safeURL.ts (hunk 2 above)
Comment (dctalbot) [reply web/src/app/util/safeURL.ts:6]: Thanks for checking, I should've known this would be weird 🙃

File: web/src/app/users/UserDetails.js [hunk 3]
```diff
@@ -198,6 +198,8 @@ export default function UserDetails(props) {
       <DetailsPage
         title={user.name + (svcCount ? ' (On-Call)' : '')}
         details={user.email}
+        noMarkdown
+        detailsStyles={{ marginBottom: '1rem' }}
```
Comment (mastercactapus) [inline web/src/app/users/UserDetails.js:202]: Instead of adding a new prop for this, can we bake it into the `DetailsPage` and just fix the margin when `noMarkdown` is set, automatically? The caller of `DetailsPage` shouldn't need to handle/override internal styles when using supported props.

**Review by mastercactapus — CHANGES_REQUESTED** [review]

File: web/src/app/users/UserDetails.js (hunk 3 above)
Comment (dctalbot) [reply web/src/app/users/UserDetails.js:202]: We could, but I think coupling this margin style to `noMarkdown` is a false relationship. But since there is only one component with the `noMakdown` prop, it would work fine and we could refactor later if needed.

Comment (dctalbot) [reply web/src/app/users/UserDetails.js:202]: https://github.com/target/goalert/pull/1290 aims to address this so I will remove the style changes in this PR

**Review by Forfold — APPROVED** [review]
functionally tested in alert details/email rendering properly on profile, lgtm!

**Review by mastercactapus — APPROVED** [review]
